spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tsp_monitor_g
    username: tsp_monitor
    password:

backend:
  api:
    package:
      base: gitlab.p1staff.com/tsp/monitor-backend/app/monitor-backend-ajaxapi
      bean:
        business: db
        http: rest
      dao: dal
      service: service
      controller: controller
      error: rest
      constant: constant
      common: common
    dir:
      base: /Users/lishouyu/deduction
      bean:
        business: model/db
        http: model/rest
      dao: dal
      service: service
      controller: controller
      error: model/rest
      constant: constant
      config: config
      common: model/common
  cmd:
    package:
      base: gitlab.p1staff.com/tsp/monitor-backend
      main: main
    dir:
      base: /Users/lishouyu/deduction
      main: main

frontend:
  dir:
    base: /Users/lishouyu/deduction-web
    store: store
    router: router
    config: config
    view: view
    api: api
