spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: codepiano
    password:

backend:
  api:
    package:
      base: gitlab.com/test/test
      bean:
        business: db
        http: rest
      dao: dal
      service: service
      controller: controller
      error: error
      constant: constant
    dir:
      base: /Users/codepiano/deduction
      bean:
        business: model/db
        http: model/rest
      dao: dal
      service: service
      controller: controller
      error: error
      constant: constant
      config: config
  cmd:
    package:
      base: gitlab.com/test/test
      main: main
    dir:
      base: /Users/codepiano/deduction
      main: main

frontend:
  dir:
    base: /Users/codepiano/deduction-web
    store: store
    router: router
    config: config
    view: view
